services:
  postgres:
    image: postgres:16.4-alpine
    container_name: dbkit_pg
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dbkit_test
      PGDATA: /data/postgres
    volumes:
      - ../.docker/pg-data:/data/postgres
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - localnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d dbkit_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: dbkit_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbkit_test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ../.docker/mysql_data:/var/lib/mysql
    networks:
      - localnet
    healthcheck:
      test: ["CMD-SHELL", "MYSQL_PWD=test mysqladmin ping -h 127.0.0.1 -u test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  clickhouse:
    image: clickhouse/clickhouse-server:25.4
    container_name: dbkit_clickhouse
    environment:
      CLICKHOUSE_DB: dbkit_test
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "127.0.0.1:9000:9000" # TCP native
      - "127.0.0.1:8120:8123" # HTTP interface
      - "127.0.0.1:9009:9009" # Inter-server communication
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --quiet --user=test --password=test http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  localnet:
    driver: bridge
