services:
  postgres:
    image: postgres:16.4-alpine
    container_name: dbkit_pg
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: dbkit_test
      PGDATA: /data/postgres
    volumes:
      - ../.docker/pg-data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - localnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d dbkit_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  localnet:
    driver: bridge
